delete-team-profile | add delete team profile function to team contro…
BreakOutEvent/breakout-backend pull request #259
Opened 2022-04-10 21:33 UTC by SimonAbat

…ller and to deletion service

2022-04-11 13:49 UTC, sibbl requested changes

2022-04-11 13:49 UTC, sibbl commented on src/main/java/backend/controller/TeamControllerV2.kt
> +        // TODO: Hier check, ob user im jeweiligen Team! und wegen weiteren Bedinungen bei Josi nachfragen
Ich glaub der Check so wie er auskommentiert ist ergibt zu 100% Sinn 👍

2022-04-11 13:49 UTC, sibbl commented on src/main/java/backend/model/user/DeletionServiceImpl.kt
> + override   fun delete(team: Team) {
Kannst es evtl noch fix wie den Rest formatieren? Danke!

2022-04-12 08:21 UTC, SimonK92 commented on src/main/java/backend/model/user/DeletionServiceImpl.kt
> + override   fun delete(team: Team) {
Done!

2022-04-12 09:22 UTC, SimonAbat commented on src/main/java/backend/controller/TeamControllerV2.kt
> +        // TODO: Hier check, ob user im jeweiligen Team! und wegen weiteren Bedinungen bei Josi nachfragen
Done.

2022-04-12 09:38 UTC, merged